# Generated by Django 5.1.7 on 2025-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='google_meet_link',
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_call_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='voice_call_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
