# Generated by Django 5.1.7 on 2025-04-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0002_remove_appointment_google_meet_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
