# Generated by Django 5.1.7 on 2025-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0003_alter_appointment_google_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='google_meet_link',
            field=models.URLField(default='https://meet.google.com/bdu-vfen-nwx'),
        ),
    ]
