# Generated by Django 5.1.7 on 2025-04-20 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0003_patientreferral_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='mediapp.patientreferral'),
        ),
    ]
