# Generated by Django 5.1.7 on 2025-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_medicalrecord_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
    ]
