# Generated by Django 5.1.7 on 2025-05-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0007_department_alter_appointment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
