# Generated by Django 5.1.7 on 2025-05-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0009_alter_appointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department_old',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
