# Generated by Django 5.1.7 on 2025-05-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0010_appointment_department_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department_old',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
