from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('service/', views.service, name='service'),
    path('price/', views.price, name='price'),
    path('contact/', views.contact, name='contact'),
    path('team/', views.team, name='team'),
    path('blog/', views.blog, name='blog'),
    path('detail/', views.detail, name='detail'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('search/', views.search, name='search'),
    path('appointment/', views.appointment, name='appointment'),
    path('book-appointment/', views.book_appointment, name='book_appointment'),
    path('patient-dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('view-appointments/', views.view_appointments, name='view_appointments'),
    path('reschedule-appointment/<int:appointment_id>/', views.reschedule_appointment, name='reschedule_appointment'),
    path('delete-appointment/<int:appointment_id>/', views.delete_appointment, name='delete_appointment'),
    path('doctor-dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('refer-patient/', views.refer_patient, name='refer_patient'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('notify-doctor/<int:appointment_id>/<str:call_type>/', views.notify_doctor, name='notify_doctor'),
    path('add-medical-record/<int:patient_id>/', views.add_medical_record, name='add_medical_record'),
    path('generate-pdf/<int:record_id>/', views.generate_pdf, name='generate_pdf'),
    path('start-video-call/', views.start_video_call, name='start_video_call'),
    path('start-voice-call/', views.start_voice_call, name='start_voice_call'),
    path('update_medical_record/<int:record_id>/', views.update_medical_record, name='update_medical_record'),
    path('delete-record/<int:record_id>/', views.delete_record, name='delete_record'),
    path('referral/<int:referral_id>/update/', views.update_referral_status, name='update_referral_status'),
    path('referrals/outgoing/', views.view_outgoing_referrals, name='view_outgoing_referrals'),
    path('referrals/incoming/', views.view_incoming_referrals, name='view_incoming_referrals'),
    path('referrals/treat/<int:referral_id>/', views.treat_referred_patient, name='treat_referred_patient'),
    path('check-treatment-status/', views.check_treatment_status, name='check_treatment_status'),
    path('add-prescription/', views.add_prescription, name='add_prescription'),
    path('delete-prescription/<int:prescription_id>/', views.delete_prescription, name='delete_prescription'),
    path('edit-prescription/', views.edit_prescription, name='edit_prescription'),
    path('get-prescription/<int:prescription_id>/', views.get_prescription, name='get_prescription'),
    path('add-note/', views.add_note, name='add_note'),
    path('edit-note/', views.edit_note, name='edit_note'),
    path('delete-note/<int:note_id>/', views.delete_note, name='delete_note'),
    path('get-appointments/', views.get_appointments, name='get_appointments'),
    path('get-patient-history/', views.get_patient_history, name='get_patient_history'),
    path('schedule-appointment/', views.schedule_appointment, name='schedule_appointment'),
    path('add-lab-result/', views.add_lab_result, name='add_lab_result'),  # Added
    
    
    path('ajax/get-departments/', views.get_departments, name='get_departments'),

    path('add-medical-record/', views.add_medical_record, name='add_medical_record'),
    path('add-user/', views.add_user, name='add_user'),
    path('edit-user/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('get-user/<int:user_id>/', views.get_user, name='get_user'),
    path('generate-system-report/', views.generate_system_report, name='generate_system_report'),
    path('get-all-appointments/', views.get_all_appointments, name='get_all_appointments'),
    path("ajax/get-treatment-details/", views.get_treatment_details, name="get_treatment_details"),

]